### ISSUE TITLE
1.0.7 SMP cannot see items in CM GUI

### ISSUE THREAD

**Issue by tgstyle** [CreativeMD/CraftingManager#25]
Single player you can see items, but in multiplayer no items are shown in the GUI at all.

**Comment by CreativeMD** [comment]
Hm, couldn't reproduce this bug :( does this always happen?

**Comment by tgstyle** [comment]
I will go ahead and close this. I cannot get it to reproduce with the latest NEI for 1.7.10 and CM 1.0.8.
