### ISSUE TITLE
Removes recipe on server

### ISSUE THREAD

**Issue by SirWilli** [CreativeMD/CraftingManager#28]
hey,

somehow CraftingManager removes the recipe of Sikly Cloth from Tinkers Construct on the server but I don't have any disabled recipe. In singleplayer it is no issue only in multiplayer.
If I open and close the CraftingManager the recipe works again until the next restart.

**Comment by CreativeMD** [comment]
Hm, which version of my mod are you using?

**Comment by SirWilli** [comment]
1.0.4 but I could reproduce it with 1.0.8 too.

**Comment by CreativeMD** [comment]
Hm, maybe i will add the author of Tinkers Construct. I will tell you if he answers

**Comment by CreativeMD** [comment]
He didn't answer yet, i hope he will read it once :(

**Comment by CreativeMD** [comment]
Please try out v1.0.14 maybe it fixes this problem.

**Comment by Bloodyny** [comment]
@ SirWilli

On the server, you need to have the same language as the client and Forge has en_us

**Comment by CreativeMD** [comment]
I recommend to use en_us for every client and server i will try to fix it, maybe i can find the mistake.

**Comment by CreativeMD** [comment]
Fixed
