### ISSUE TITLE
Mod dosnt work on the Cauldron 1.7.10

### ISSUE THREAD

**Issue by Smarttracer** [CreativeMD/CraftingManager#29]
Recipes are clear after closing the GUI and written "0 recipes saved" in message.
In SSP everything works well. But not cauldron.
Not worked all versions after 0.7.5

**Comment by CreativeMD** [comment]
Please report this to cauldron. I will try to contact them soon.

**Comment by Smarttracer** [comment]
Thanks

**Comment by CreativeMD** [comment]
it should be fixed, at least it worked out for me.
