### ISSUE TITLE
GregTech compatibility and minor bug

### ISSUE THREAD

**Issue by LuxusDarkangel** [CreativeMD/CraftingManager#30]
Minor bug: Crash when you click 2 or 3 times the save button when adding a recipe.

GregTech compatibility: Using CraftingManager 1.0.9 for minecraft 1.7.10, when I disable or add any recipes, GT recipes stop working, and i have to restart the server. Also GT furnace recipes only works on Thermal Expansion's Redstone Furnace since i'm using CM (it's not working with vanilla furnaces, or, for example, Thaumcraft's Infernal Furnace).

More info: GregTech version: 5.07.07, Forge version: 10.13.2.1232
Other info: I disabled the "Ensure to be loaded last" feature from the GT config (located at GregTech.cfg -> general), if i enable it, any recipe from GT works (only when using it with CM)

If you need to know anything more (maybe my list of mods and its versions?), just ask for it :)

**Comment by CreativeMD** [comment]
Could you try if this file fixes this bug?
https://www.dropbox.com/s/rbfs0scezijkr0b/zCraftingManager%20ALPHA%201.0.10%20mc1.7.10.jar?dl=0
i named my mod zCraftingManager maybe this could help. Before i only named the jar zCraftingManager.

**Comment by LuxusDarkangel** [comment]
Yes, now CM is loading after GT and the problem is solved, thank you so much :3
(Obviously the minor bug isn't fixed, but it's just that, a minor bug, anything important)

**Comment by CreativeMD** [comment]
Really :D, that's awesome. Will release a fix for this soon.

**Comment by LuxusDarkangel** [comment]
Just an anotation: This fix only work if you disable from the GT cfg the Ensure to be loaded last option (I suppose it overrides the alphabetical order)

**Comment by CreativeMD** [comment]
Sorry, having some troubles, will release this fix tomorrow.
