### ISSUE TITLE
Smart Moving Compatibility. Change isSneaking for Key Sneak press check

### ISSUE THREAD

**Issue by anion155** [CreativeMD/CraftingManager#31]
Smart Moving has been remastered sneaking mechanism. So now isSneaking method is false in flying or when on player ladder on vine, even if sneak key pressed.
Could you change isSneaking() method in EnityItem Custom Pick Up to Sneak key pressing?

**Comment by anion155** [comment]
Sorry miss with mod )). I mean it for ItemPhysics

**Comment by CreativeMD** [comment]
Cannot do this for server side.
