### ISSUE TITLE
CraftingManager memory leak?

### ISSUE THREAD

**Issue by LuxusDarkangel** [CreativeMD/CraftingManager#32]
Since i'm using CM TPS from my server are going down. It sometimes send me this message:

[03:01:15 ERROR]: Detected ongoing potential memory leak. 500 packets have leaked. Top offenders
[03:01:15 ERROR]:        CMPacket : 497
[03:01:15 ERROR]:        FML : 3

**Comment by CreativeMD** [comment]
That is a memory leak, but it shows how many packets are send. Not an issue.

**Comment by LuxusDarkangel** [comment]
It's not showing how many packets are sended, it's showing how many packets (from all) are leaked (violations), so that's a big issue.

**Comment by CreativeMD** [comment]
No, that is not an issue ...
Sorry i write that this would be a memory leak :D , but i wanted to say that this is non memory leak.
This message comes up if your server has problems to handle all the packets, it shows how many packets were send from which mod, not a problem of my mod, but your server is not fast enough to handle the situation properly.

**Comment by LuxusDarkangel** [comment]
Ok, i've been using JD to take a look to your network code, and it's outdated, that's why its causing memory leaks, as you can see here: http://www.minecraftforge.net/wiki/Tutorials/Packet_Handling
You need to update it (here you have a very nice tutorial to do this: http://www.minecraftforum.net/forums/mapping-and-modding/mapping-and-modding-tutorials/2137055-1-7-x-1-8-customizing-packet-handling-with)

**Comment by CreativeMD** [comment]
Never heard about that, but my system works for now (tested it very often), YES if this cause memory leaks i will change my system of course. Will add this to my ToDo List.

**Comment by LuxusDarkangel** [comment]
Thanks :). Sorry for bug you so much, but this causes server TPS to drop A LOT, so i think that's good for you to fix it, so more people can use your mod n.n

**Comment by LuxusDarkangel** [comment]
Can i ask for a ETA?

**Comment by CreativeMD** [comment]
ETA?
but anyway i will release a fix of this today, hopefully it works out :D

**Comment by LuxusDarkangel** [comment]
ETA =  a date for the release, but you already said it.

**Comment by CreativeMD** [comment]
It's already out :D
