### ISSUE TITLE
Crafting Manager w/Buildcraft Additions

### ISSUE THREAD

**Issue by HCSarise** [CreativeMD/CraftingManager#33]
I discovered today that Crafting Manager somehow disables the recipes in Buildcraft Additions. Buildcraft Additions uses the Eureka crafting system, and somehow these two interfere with each other.

**Comment by CreativeMD** [comment]
Maybe it's similar to greg tech, disable that the mod wants to be the last which loads.

**Comment by AEnterprise** [comment]
someone also reported this bug on my end, i checked and BCA isn't activly requesting to be the last loaded mod, it does load after Buildcraft and Eureka because it depends on there api's

is there anything i can do on my end to fix this?

**Comment by CreativeMD** [comment]
Hm, not really, every recipe added after my mod has load will be removed one an update occurs.
Have no idea how to fix this :(

**Comment by AEnterprise** [comment]
one possible fix is to make sure your mod loads last, maybe add 'ZZZ' as start for your mod's jar file?

**Comment by AEnterprise** [comment]
also what is the modID for this mod? i'll put it in my @Mod annotation to make sure it BCA loads BEFORE crafting mananger

**Comment by CreativeMD** [comment]
...
my modid is zCraftingManager, it should load after BCA.

**Comment by AEnterprise** [comment]
clearly it isn't so i'll see if this fixes it

**Comment by AEnterprise** [comment]
forgot a bit about this but i added it to the annotation: https://github.com/BCA-Team/Buildcraft-Additions/commit/0ad52ed3089de13c7aa76f07f8e150258aff613c

@HCSarise could you try with this build please?
http://ci.tterrag.com/job/Buildcraft-Additions/86/

**Comment by HCSarise** [comment]
Using Crafting Manager version 0.7.5 I get the following crash: http://pastebin.com/SSusStSw

I also tried in on the Alpha Crafting Manager version ALPHA 1.0.12 and the game does not crash but the recipes are still gone. No recipes to be seen in NEI, and even if I make what I know is the basic duster recipe in a crafting table it doesn't come up with any output.

**Comment by AEnterprise** [comment]
any update on this? i'm not doing anything special with my recipes nor am i using a custom crafting handler, the issue must be on this side

**Comment by CreativeMD** [comment]
oh you are the author of BuildCraft Additions :D
I don't know what is causing the problem, when do you add these recipes?

**Comment by AEnterprise** [comment]
the recipes depend on BC being loaded so they are added with the rest of the mod integration stuff so in the doneLoading phase (to make sure all things from the other mods are initialized and usable)

**Comment by CreativeMD** [comment]
Hm, never really looked what event is the last one ...
I'm using FMLServerStartingEvent

**Comment by AEnterprise** [comment]
i have no idea how your mod works so i have no idea what the cause of this issue might be, as for what event comes last i don't know for sure, i sugest asking that to the forge guys

**Comment by CreativeMD** [comment]
Ok :D, but i think yours obviously is after FMLServerStartingEvent will take a look into the code.

**Comment by AEnterprise** [comment]
whell you'll have to find a way around that then cause there are a few of mods that use research that don't register crafting recipes until you unlocked the research, also there are quite alot of mods that wait pretty long with registering recipes for the same reason BCA does it: loading a different set of recipes depending on the mods that are installed

**Comment by CreativeMD** [comment]
Could you try out this file?
https://www.dropbox.com/s/08umiyqe4gr3pnm/zCraftingManager%20ALPHA%201.0.14%20mc1.7.10.jar?dl=0

**Comment by CreativeMD** [comment]
It doesn't work, it is obviously not the event, but i have no idea why these recipes should be left out :O

**Comment by AEnterprise** [comment]
i duno, as i said: there is nothing special on my end, i think you're gona have to use the debugger to find out what's going on

**Comment by CreativeMD** [comment]
Do you have a source download link?

**Comment by AEnterprise** [comment]
https://github.com/BCA-Team/Buildcraft-Additions

also if it turns out to be something on the BCA side of things could you make a PR to fix it then? i don't have access to your code so i can't fix it

**Comment by CreativeMD** [comment]
Only use this Issues page of github, maybe i will upload craftingmanager some time :D

**Comment by AEnterprise** [comment]
i know, i don't realy care if you upload it or not, it's your mod so do with it what you want, just stating that i can't even try to begin to figure out the problem as i have no idea how your mod handles things without code

**Comment by CreativeMD** [comment]
Oh, damit ... my mistake ... forgot that loadConfig loads all recipes from the craftingmanager :D using the FMLPostInitializationEvent

**Comment by AEnterprise** [comment]
thanks for fixing this bug :)
