### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by save99** [CreativeMD/CraftingManager#34]
I have a new mod setup i made with TFC ( TerraFirmaCraft) and after i add mor then 30 recipes the game crashes and ses something along the lins of cannot exceed something of 32k... and adding new continuing to open the world and trying to add recipes in cases more crashes.. my most current crash resulted in this...http://pastebin.com/gT4HN8FH
try to fix this thingy i need to change some more recipes X.x

**Comment by CreativeMD** [comment]
Sorry, forgot this issue, we take a look at that.

**Comment by CreativeMD** [comment]
Maybe try out 1.0.13?

**Comment by wormmu** [comment]
I'm using 1.0.16 Alpha, on Sky Factory 2.3, and I am receiving the error.  Payload may not be over 32k.  Here's my log:  http://paste.ee/p/qiWJP

I have 55 recipes in, and cannot seem to add anymore.  Is this the limit?

**Comment by wormmus** [comment]
I'm using 1.0.16 Alpha, on Sky Factory 2.3, and I am receiving the error. Payload may not be over 32k. Here's my log: http://paste.ee/p/qiWJP

I have 55 recipes in, and cannot seem to add anymore. Is this the limit?
