### ISSUE TITLE
NEI integration issues

### ISSUE THREAD

**Issue by tgstyle** [CreativeMD/CraftingManager#37]
When running NEI and typing in the Crafting Manager search field, it will open NEI windows or close NEI completely, and can close the Crafting Manager window.

Pressing O closes NEI, pressing P opens potions, etc...

**Comment by CreativeMD** [comment]
Yes, really annoying ... already working on a fix for this.

**Comment by tgstyle** [comment]
Good to hear, keep up the good work!

**Comment by CreativeMD** [comment]
Fixed it will be in the next version
