### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/CraftingManager#38]
I use version: 1.0.13
This in-game image: http://i.hizliresim.com/RJp1XG.png
this cfg file: https://www.mediafire.com/?9ii25r95htid6em

Please correct EMERGENCY

Attached is no problem in the recipe.
problem described in the disabled.

**Comment by CreativeMD** [comment]
Hm, shouldn't happen, if you search 'disabled' in the config menu what recipes are shown?

**Comment by anar4732** [comment]
I do not understand.
I use google translation.
please type it a more open manner.
@CreativeMD

**Comment by anar4732** [comment]
This problem only happens sometimes.
sometimes can not be.
sometimes config correctly recorded in some way.
sometimes only 'Disabled' is not the record.

When not properly config record.
if I exit the game
I have entered a 'disabled 0 recipes' is written.

I use google translate very difficult to explain.
I know you isd make a video?
@CreativeMD

**Comment by CreativeMD** [comment]
Are you german?

**Comment by anar4732** [comment]
no.
Turkish

**Comment by CreativeMD** [comment]
It is hard to help you, but maybe try out v1.0.14

**Comment by anar4732** [comment]
Watch the video:
 http://youtu.be/QfZuevbUo4A
@CreativeMD

**Comment by CreativeMD** [comment]
hm, that is really awkward :O will take a look at it.

**Comment by CreativeMD** [comment]
are you using cauldron?

**Comment by anar4732** [comment]
What does that mean?

**Comment by CreativeMD** [comment]
Never mind, i have no idea why this is happening.

**Comment by anar4732** [comment]
I am backing up.
http://i.hizliresim.com/lkRzaQ.png

**Comment by anar4732** [comment]
my windows Turkish.
This causes errors in some modes.
Could it be a problem?
@CreativeMD

**Comment by CreativeMD** [comment]
Hm, maybe don't know :O

**Comment by CreativeMD** [comment]
i think it was a language issue
