### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/CraftingManager#39]
by any mode all recipes
To disable
If you add something
would be super.

**Comment by CreativeMD** [comment]
? didn't get it

**Comment by anar4732** [comment]
To add a method to disable
all recipes in a mode
@CreativeMD

**Comment by CreativeMD** [comment]
this is already avaiable :O?

**Comment by anar4732** [comment]
how?
example: I have all the recipes in bulidcraft mode
disable one-touch circuit
@CreativeMD

**Comment by Cracks777** [comment]
is it possible to add other items as fuels?

**Comment by CreativeMD** [comment]
This is not an issue, please post ideas in the minecraftforum thread.
