### ISSUE TITLE
Latest version .14 does not work with SMP

### ISSUE THREAD

**Issue by tgstyle** [CreativeMD/CraftingManager#40]
Network errors on connection.

http://paste.ubuntu.com/10575584/

**Comment by Cracks777** [comment]
mine doesnt say that but if i load the game and go directly to my server it boots me and tells me an error has occured, i think its due to the config being sent to the client.

**Comment by CappyT** [comment]
Same here.
Client: Using Forge 1307 (this one here: http://files.minecraftforge.net/minecraftforge/1.7.10) + Liteloader .04

The server is using Cauldron 1.7.10 with forge 1307. No errors there.

Client complete logfile: http://pastebin.com/hDCyVspV

**Comment by CreativeMD** [comment]
Sorry, but don't use cauldron :(, test it with Forge Server 10.13.2.1291 everything works fine.

**Comment by tgstyle** [comment]
I am not using cauldron, I am using forge 10.13.2.1291

**Comment by tgstyle** [comment]
Here is the config that works fine in .13
http://paste.ubuntu.com/10582342/
This is the mods list. Maybe cracks could review it and let us know what similar mods are being used?
http://paste.ubuntu.com/10582348/

**Comment by Cracks777** [comment]
i use a cauldron server, but the version before this one works fine

**Comment by Cracks777** [comment]
i dont think its a problem with another mod tho, its when the server sends the client the config, something is getting messed up there

**Comment by Cracks777** [comment]
tgstyle is it crashing you? or is it just rejecting the connection

**Comment by tgstyle** [comment]
It just gives an error on the connection, neither the server or client crash.

**Comment by Cracks777** [comment]
tgstyle is there a way i can contact you other than on this post?

**Comment by tgstyle** [comment]
Hmm not sure how to do that, certainly don't want to post anything personal in a public forum.

**Comment by Cracks777** [comment]
do you use teamspeak

**Comment by tgstyle** [comment]
In .15 this is still an issue for me. Forge Server 1291.
Connecting to a server it just says "A Fatal Error has occured, this connection is terminated"

The client is now logging this error.
http://paste.ubuntu.com/10601488/

**Comment by CreativeMD** [comment]
Fixed it in v1.0.16
