### ISSUE TITLE
Disabled recipes don't always survive opening the GUI

### ISSUE THREAD

**Issue by tgstyle** [CreativeMD/CraftingManager#41]
After disabling recipes, and after a couple world reloads. Some disabled recipes tend to enabled themselves again after you open the GUI and make changes. I will see if I can get the exact details to reproduce it, and if there are any error logs.

Edit: Crafting Recipes, smelting recipes appear to be unaffected.

**Comment by tgstyle** [comment]
It seems to revolve around recipes in the irecipe section of the config. I cannot nail down an exact way to reproduce. Just that the mods I have installed, certain disabled recipes will stay disabled and others will not upon opening the GUI. At this point I have to piece together a config by disabling them on a seperate system, then put them in manually. This is all SMP btw.

**Comment by CreativeMD** [comment]
Someone else also reported this bug, i will try to fix this in a week.

**Comment by tgstyle** [comment]
Latest version appears to have fixed this.

**Comment by CreativeMD** [comment]
nice
