### ISSUE TITLE
How does Ore Dictionary in a recipe work?

### ISSUE THREAD

**Issue by tgstyle** [CreativeMD/CraftingManager#43]
I have added a recipe with the ore dictionary option and it does say the right ore dictionary name. However, the recipe still only works for the item used, not the ore dictionary value. Example Iron Nuggets to an ingot, if I used Thermal Foundation Iron nuggets with the ore dictionary option, it still only worked with Thermal Foundation and not Tinkers Iron nuggets (disabled the mods recipes to test).

**Comment by CreativeMD** [comment]
Hm, i used the ore dictionary feature very often and it worked.
Did you checked if they have the same ore dictionary name?

**Comment by tgstyle** [comment]
Yes, they both have the nuggetIron ore dictionary entry. Also note this was SMP.

**Comment by CreativeMD** [comment]
Will do some testing, using my mod in a huge modpack, and it's SMP :D.

**Comment by CreativeMD** [comment]
Yes, nuggets are not working, will try to fix this soon.

**Comment by tgstyle** [comment]
I cannot get it to work with ingots either, I have only tried ingotCopper.

**Comment by tgstyle** [comment]
Also just tried a blockCopper. Did not work.

**Comment by CreativeMD** [comment]
Fixed it will be in 1.1.0
