### ISSUE TITLE
version update bug

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/CraftingManager#44]
0:13 I updated version 0.17 ate.
and there was not described the disabled.
There were 150 disabled. You're 10.
0:13 back version. and improved.

--------------------------------------------------------

This text was translated by google translation.
Original language: Turkish

**Comment by CreativeMD** [comment]
Sorry, but i can't understand you at all :O

**Comment by anar4732** [comment]
I'll try to explain better.
I currently: 1.0.13
I tried to update: 1.0.17
After updating: all recipes have been destroyed.
back to 1.0.13: Fix sorna

-------------------------------------------------- -----------------------

This text was translated by google.
It can be difficult to understand.

@CreativeMD

**Comment by CreativeMD** [comment]
Hm, yes this can happen, but using 1.0.17 is safer. I recommend to redo your work, sorry about that.

**Comment by anar4732** [comment]
1.0.18 properly please?
I have 200 recipes disabled.
very difficult to set them all again.

**Comment by anar4732** [comment]
otherwise uses the 1.0.13 on other users like me.
@CreativeMD
