### ISSUE TITLE
Steves Factory Manager recipe issue

### ISSUE THREAD

**Issue by tgstyle** [CreativeMD/CraftingManager#46]
I have another item to report. I am not sure when this happened exactly as it used to work fine. However, upon a world reload in SSP or SMP, I have to refresh a custom Crafting Manager crafting recipe in Steves Factory Manager in order for it to work in the crafter again. Any crafting recipe that is not from Crafting Manager seems to work fine in the crafter after a world reload. Usually just updating one item in the recipe will get it to take and it will start working fine.

**Comment by CreativeMD** [comment]
Hm, i will contact the author pretty soon.

**Comment by tgstyle** [comment]
Just a quick not that this effort is now under way.
https://github.com/hilburn/AdvancedFactoryManager

**Comment by CreativeMD** [comment]
Can't find it :O

**Comment by tgstyle** [comment]
I tried Minetweaker to see if it had the issue, it works fine.

**Comment by CreativeMD** [comment]
Nice :D ok.
