### ISSUE TITLE
Mekanism v8 does not take smelting recipes

### ISSUE THREAD

**Issue by tgstyle** [CreativeMD/CraftingManager#49]
If you add smelting recipes, mekanism v8 does not recognize them in a smelter/factory.

CM 1.0.17

**Comment by CreativeMD** [comment]
Sorry, this isn't a bug of mine. Please report this to the author of mekanism.

**Comment by tgstyle** [comment]
I tried minetweaker just to see if it was Mek 8, it works fine.
