### ISSUE TITLE
server bug EMERGENCY

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/CraftingManager#52]
We are creating a modpack that contains your mod but we have a huge situation. We have decided that the crafting of some items are too easy and we want to use your mod to change the recipes. In single player we arranged all of the recipes that we wanted to change. The problem is the when we copy the 71 kb new1.cfg file some of the recipes that we have disabled are broken. In single player we have 300 recipes disabled but when we copy the same file to the server there is only 169 recipes disabled.  When we try to change the recipes on the server the recipes behaves like they havent been disabled. (original recipes are still there). We really have to solve this problem soon because the pack will be published in tree days . Also we are opening a server with the pack. There are a lot of people waiting for the server at the moment. We have to solve this problem soon. Thank you for your interest.

**Comment by CreativeMD** [comment]
So, you cannot disable these recipes in the server? Which version do you use? What recipes aren't disabled (maybe recipes from a particular mod)?

**Comment by anar4732** [comment]
versiyon: 1.0.17
 I have this problem in all modes

**Comment by CreativeMD** [comment]
Redisabling doesn't work?

**Comment by anar4732** [comment]
no

**Comment by CreativeMD** [comment]
Could you send me the config files?

**Comment by anar4732** [comment]
https://www.dropbox.com/s/yayc2bgag6ps274/new1.cfg?dl=1
