### ISSUE TITLE
language bug

### ISSUE THREAD

**Issue by anar4732** [CreativeMD/CraftingManager#53]
There is a problem with the language compatibility. For example when you make changes in the recipes in A language and open a server in B language the recipes wont work.  I'll suggest you to use the items ID instead of the names in the config file.

**Comment by CreativeMD** [comment]
Which version do you use, because it uses the minecraft names. Example minecraft:stone that should fit in every case.

**Comment by anar4732** [comment]
1.0.17 = 1.7.10

**Comment by CreativeMD** [comment]
could you send me your config file for each language?

**Comment by anar4732** [comment]
https://www.dropbox.com/s/yayc2bgag6ps274/new1.cfg?dl=1
config doesn't change when you change the language....

**Comment by CreativeMD** [comment]
Yes, but why should there be a problem if the config doesn't change :O?
