### ISSUE TITLE
Crafting manager doesnt work!

### ISSUE THREAD

**Issue by FurxFolf** [CreativeMD/CraftingManager#54]
Heres screenshot, i found it in the server console, hope it will help to solve the problem.
Version "zCraftingManager ALPHA 1.0.18 mc1.7.10" "CreativeCore v1.2.2 mc1.7.10"
![lok](https://cloud.githubusercontent.com/assets/13664874/9093652/f8148dce-3bb5-11e5-97bb-6fdf73f36d73.PNG)

**Comment by FurxFolf** [comment]
When I type /CraftingManager, i get the gui, but i cant go to disabling or changing craft window, It simply does nothing when i click on the gui. Please help me with this.

**Comment by FurxFolf** [comment]
Btw, I ALWAYS get my textures of items dying when I use zCraftingManager 0.7.7 mc1.7.10 (an old version cause I cant use the newest one due to that problem above), heres a screenshot. 
![222222222222222222](https://cloud.githubusercontent.com/assets/13664874/9094379/1eec4ba4-3bba-11e5-92e6-9c4491ec4306.PNG)

**Comment by CreativeMD** [comment]
You can open the gui but you can't disable recipes?
Do you know how to do it?

**Comment by FurxFolf** [comment]
Ohh, thanks for answer!
No, I do know how to do anything in your mod, cause I really love It and I use It alot, I just wanted to update to the newest version. Ill send u a screenshot in 5 mins, to explain whats the problem

**Comment by CreativeMD** [comment]
ok :D

**Comment by FurxFolf** [comment]
Here It Is! When I click these buttons (i pointed them with red arrows) nothing happens! 
![r23r23r23r32](https://cloud.githubusercontent.com/assets/13664874/9097160/8c269ff2-3bca-11e5-869e-c34933390305.PNG)

**Comment by CreativeMD** [comment]
oh :D press 'o'

**Comment by FurxFolf** [comment]
Ohh! lol... Thanks alot! I guess you have to write about it on yours mod page, so noone will have the same silly problem as I did :D
But still have a little problem, Ill show you a screenshot in a minute

**Comment by FurxFolf** [comment]
Here, there are no crafting recipes for like about 15-20% of items, there is no crafting recipes for industrial craft and for thermal expansion, and some crafting recipes from other mods are also missing. Is it fine, or I can fix it somehow?
![123](https://cloud.githubusercontent.com/assets/13664874/9097370/efa5917c-3bcb-11e5-96b5-818ab0cd894d.PNG)
![1234](https://cloud.githubusercontent.com/assets/13664874/9097369/efa496dc-3bcb-11e5-8ca5-f8997f4a9b5d.PNG)
![12345](https://cloud.githubusercontent.com/assets/13664874/9097371/efa7c5f0-3bcb-11e5-8557-76378ad4d182.PNG)

**Comment by CreativeMD** [comment]
This is not an issues, this mod doesn't support all recipes.

**Comment by FurxFolf** [comment]
Ahh ok then :D 
Thanks you alooooot, you really helped me out, and thanks for answering me so quickly, so i didnt even have to wait for tomorrow :)
