### ISSUE TITLE
Crafting manager doesnt disable more than 80 crafts!

### ISSUE THREAD

**Issue by FurxFolf** [CreativeMD/CraftingManager#55]
Hello again, when I try to disable more than about 80 crafts, my previous disables appear to be lost
![default](https://cloud.githubusercontent.com/assets/13664874/9138476/c9bd1cac-3d2c-11e5-82b3-8224c9d648f2.PNG)

**Comment by FurxFolf** [comment]
Disabled 8 crafts more, and lost almost all the previous disables
![21442](https://cloud.githubusercontent.com/assets/13664874/9138572/5b81ee56-3d2d-11e5-823e-d529be2a86c0.PNG)
Please help me with this issue

**Comment by CreativeMD** [comment]
Hm and nobody edited something? Which version do you use?

**Comment by FurxFolf** [comment]
Hey! No, Im the only one who is using this mod on the server. 
Version of the game is 1.7.10, version of your mod is  the latest "zCraftingManager ALPHA 1.0.18 mc1.7.10"

**Comment by FurxFolf** [comment]
Accidentally closed the issue

**Comment by FurxFolf** [comment]
Can you help me with this problem please?

**Comment by CreativeMD** [comment]
Sorry, but i have no clue what is happening
i'm working on a rewrite for CraftingManager, maybe this fixes this bug.

**Comment by FurxFolf** [comment]
Ahh, understood. Maybe I can help you somehow? I may send you my server with its mods, so maybe itll help you to find the issue

**Comment by CreativeMD** [comment]
It's a complete rewrite,
we will see if it works once it's out.

**Comment by FurxFolf** [comment]
Ok, understood, so I cant help?

**Comment by CreativeMD** [comment]
Not really, you have to wait until the new update, sorry about that. I'm doing my best to finish this update as soons as possible.

**Comment by FurxFolf** [comment]
Ok, thanks alot dude

**Comment by Bloodyny** [comment]
Hello

I've noticed that if you change the language in which "disabling crafting recipes" varied on the number of recipes, added crafting recipes and added recipes furnace remains unchanged. My guess is the whole in the config to run on ID's since then is no error while changing the language. I had wondered already in multiplayer and local I had asked to see the German and the config has changed.

**Comment by FurxFolf** [comment]
The problem is, I cant  disable crafts,  I can add it, but I cant disable them

**Comment by Bloodyny** [comment]
I have the problem with the disable on the Nitrado server that has a different language and it does not accept the change. At each restart, the changes are gone.

**Comment by Bloodyny** [comment]
I just found the Forge takes as default language en_us. I had been German and English UK now I will test it in English and I am sure that the US Config is me alas unchanged every restart. You got a problem as far as the multiplayer so I read that right?

**Comment by CreativeMD** [comment]
Should be fixed in the newest version
