### ISSUE TITLE
Ask for ID or languages ​​Integration

### ISSUE THREAD

**Issue by Bloodyny** [CreativeMD/CraftingManager#56]
First ... a really good mod got what you wrote there, indispensable!

The disabling functions recipes accepts no storage if one converts the client to another language. Conclusion I have to create my Modpack the config in three languages. And let's run with every change the whole 3 and then reinkopieren. For added Furnace recipes and recipes added all goes in all languages. Can you please We'll see what's wrong in the transfer to the Config. Or my idea would leave everything to transmit in ID's.

thanks!

I am German and have translated babelfish.de

**Comment by CreativeMD** [comment]
du kannst Deutsch sprechen :D
Ich habe IDs schon davor genutzt, diese sind aber seid 1.7 von Welt zu Welt unterschiedlich, deswegen habe ich die Namen genommen, diese sind aber nicht nur eigentlich sprach unabhängig :(

**Comment by Bloodyny** [comment]
Ein Deutscher Mod schreiber coole Sache!

Deutsche Config sieht so bei mir auch, bei addsmelting Ausgabe "S:minecraft/s02spider_eye;I:1;I:0;S:null;};ItemStack:{S:minecraft/s02stone;I:1;I:0;S:null;};}"=true" und bei irecipe "B:"R-I-diamant;truhe;diamant;truhe;null;truhe;diamant;truhe;diamant;-O-tile.multipagechest|MultiPageChest:multipagechest|0|1"=false
", bei shaped auch "B:"R-I-eisenbarren;eisenbarren;eisenbarren;eisenbarren;null;eisenbarren;feder;null;feder;-O-item.speedlegs|null|0|1"=false". Bei irecipe sollte vielleicht auch die gleiche ausgabe wie bei addsmelting stehen weil da geht es ja wenn ID's eher schlecht sind. "B:"{I:3;I:3;ItemStack:{S:minecraft/s02vine;I:1;I:0;S:null;};ItemInfo:{I:0;S:minecraft/s02leaves;S:;S:;};S:null;ItemInfo:{I:0;S:minecraft/s02leaves;S:;S:;};ItemInfo:{I:0;S:minecraft/s02leaves;S:;S:;};ItemInfo:{I:0;S:minecraft/s02leaves;S:;S:;};ItemInfo:{I:0;S:minecraft/s02leaves;S:;S:;};ItemInfo:{I:0;S:minecraft/s02leaves;S:;S:;};S:null;ItemInfo:{I:0;S:minecraft/s02leaves;S:;S:;};}"=true
" steht bei addshapedore geht auch alles. Ich meine damit das alle Sprache mit der ausgabe von addshapedore und addsmelting problemlos gehen nur halt irecipe und shaped nicht. Die anderen Funktionen habe ich nicht ausprobiert.

https://www.dropbox.com/s/2by2dqa5pmp34i6/anzahl.png?dl=0

Wenn du magst kannste es mal testen. Das ist mein Modpack, in den Config Ordner siehste wie es gemacht habe das ich bei drei Sprachen die gleiche Config habe.
http://www.technicpack.net/modpack/survival-hd.682884

**Comment by CreativeMD** [comment]
Sollte mit der neusten Version behoben sein.
